name: Build Drone Dataset

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install --upgrade pip
      - name: Build processed dataset
        run: ./scripts/build_dataset.py
      - name: Commit processed artefacts
        run: |
          if [[ -n "$(git status --short data/processed)" ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add data/processed
            git commit -m "chore: refresh processed dataset"
            git push
          else
            echo "No changes to commit"
          fi
